### ISSUE TITLE
First run fails to set user_id

### ISSUE THREAD

**Issue by tanc** [Pomax/flickrmirror#23]
After initial set up the first run appears to have failed with some kind of validation error. Is there any way to re-run it?
```
Error: cannot set user_id to 9840317@N07; validation failed.
    at Object.defineProperty.set (/home/tanc/flickrmirror/lib/models/UserModel.js:82:22)
    at /home/tanc/flickrmirror/lib/models/UserModel.js:89:16
    at Array.forEach (native)
    at new UserModel (/home/tanc/flickrmirror/lib/models/UserModel.js:87:27)
    at /home/tanc/flickrmirror/lib/firsttime.js:37:20
    at /home/tanc/flickrmirror/node_modules/flickrapi/src/FlickrAPI.js:127:43
    at process._tickCallback (node.js:415:13)```

**Comment by Pomax** [comment]
If you haven't written the `.env` file (or set the environment variables that the library needs), it'll keep first-running until you do, so you should be able to just rerun it and walk through the auth process again by running the process without any environment variables set (either at the shell level or via `.env` file).

**Comment by tanc** [comment]
That doesn't appear to happen for me. I've deleted the .env file and then run `node app` and this is the output:
```
node app
running flickrmirror with hostname: undefined
express deprecated app.configure: Check app.get('env') in an if statement lib/appconfiguration.js:17:9
connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:56:20
connect deprecated limit: Restrict request size at location of read node_modules/express/node_modules/connect/lib/middleware/multipart.js:86:15
connect deprecated methodOverride: use method-override npm module instead lib/appconfiguration.js:27:23
Node server listening on http://127.0.0.1:undefined
```

**Comment by Pomax** [comment]
this is if you follow the steps in the readme? I'm not able to test this right now but I might be able to have a look at this tomorrow.

**Comment by tanc** [comment]
I followed the instructions in the readme. The first run allowed me to enter details and it looked like it was working up until the point where you add the token code from flickr authentication. After that I can't re-run or add a user.

**Comment by Pomax** [comment]
what if you delete the `.env`, copy `env.dist` as a new `.env`?

**Comment by tanc** [comment]
alas, just the same

**Comment by jptime** [comment]
I had to edit the UserModel.js file and change the user_id check to return true.
It's checking if the value has "%40" in it which my user_id did not.

`user_id: {
    label: "your Flickr user id (e.g. 123456789@N01)",
    type: "text",
    machinevalue: true,
    check: function(v) { return v.indexOf("%40") > -1; }
  },`

Set the return to == -1 and try again @tanc 
@Pomax it's a dirty hack, but I was able to get my pictures down.

**Comment by Pomax** [comment]
interesting. What format does your user_id use if not the `\d+@N\d+` format?

**Comment by jptime** [comment]
Thats the right format, it's just the check function that is failing. 
Is the '%40' supposed to be in the user_id? Or is it checking a different value?
My Flickr account isnt very old.

**Comment by Pomax** [comment]
`%40` is the character `@`, HTML encoded.
